"""Smoke test against the deployed HeatShift API.

Verifies the critical path:
1. Register a site
2. Force a replan
3. Check plan exists and was evaluated by Cedar
4. Confirm the shift change via API
5. Verify metrics incremented
"""

import os
import sys
import time
import requests

API_URL = os.environ.get("NEXT_PUBLIC_API_URL", "http://localhost:3000")

def main():
    if not API_URL or API_URL == "http://localhost:3000":
        print("Set NEXT_PUBLIC_API_URL to the deployed API endpoint.")
        sys.exit(1)
        
    print(f"Testing against {API_URL}")
    
    # 1. Register a site
    site_payload = {
        "name": "Smoke Test Site",
        "zone_id": "okhla_industrial",
        "worker_count": 20,
        "over50_share": 0.1,
        "unshaded": True,
        "heavy_labor": True,
        "shift_start": 8,
        "shift_end": 18
    }
    
    print("1. Registering site...")
    r = requests.post(f"{API_URL}/sites", json=site_payload)
    if r.status_code != 201:
        print(f"Failed to register site: {r.text}")
        sys.exit(1)
        
    site_id = r.json()["site"]["site_id"]
    print(f"  Site ID: {site_id}")
    
    # 2. Force replan
    print("2. Forcing replan...")
    r = requests.post(f"{API_URL}/sites/{site_id}/replan")
    if r.status_code != 202:
        print(f"Failed to replan: {r.text}")
        sys.exit(1)
        
    # Wait for async plan generation
    print("  Waiting 15 seconds for plan generation...")
    time.sleep(15)
    
    # 3. Check plan
    print("3. Checking plan...")
    r = requests.get(f"{API_URL}/sites/{site_id}/plans")
    if r.status_code != 200:
        print(f"Failed to get plans: {r.text}")
        sys.exit(1)
        
    plans = r.json().get("plans", [])
    if not plans:
        print("  No plans generated!")
        sys.exit(1)
        
    latest_plan = plans[0]
    print(f"  Plan ID: {latest_plan['plan_id']}")
    print(f"  Generated by: {latest_plan['generated_by']}")
    
    # Check trace for Cedar
    cedar_calls = [t for t in latest_plan.get("trace", []) if "cedar" in t.get("tool", "")]
    if not cedar_calls and latest_plan["generated_by"] == "agent":
        print("  WARNING: Agent plan has no Cedar trace!")
        # We don't fail here because it might have fallen back to rules
        
    # 4. Confirm shift change
    print("4. Confirming shift change...")
    confirm_payload = {
        "site_id": site_id,
        "plan_id": latest_plan["plan_id"],
        "decision": "confirmed"
    }
    r = requests.post(f"{API_URL}/confirmations", json=confirm_payload)
    if r.status_code != 201:
        print(f"Failed to confirm: {r.text}")
        sys.exit(1)
        
    print("  Confirmed.")
    
    # Wait for metrics to update (DynamoDB streams -> Lambda might take a second)
    time.sleep(2)
    
    # 5. Verify metrics
    print("5. Verifying metrics...")
    r = requests.get(f"{API_URL}/metrics")
    if r.status_code != 200:
        print(f"Failed to get metrics: {r.text}")
        sys.exit(1)
        
    metrics = r.json().get("metrics", {})
    print(f"  Total Confirmed: {metrics.get('total_sites_confirmed')}")
    print(f"  Exposure Avoided: {metrics.get('total_exposure_hours_avoided')}")
    
    if metrics.get("total_sites_confirmed", 0) == 0:
        print("  Metrics did not update correctly!")
        sys.exit(1)
        
    print("\n✅ Smoke test passed!")

if __name__ == "__main__":
    main()
